### ISSUE TITLE
Higher amount of reuse of Dublin Core

### ISSUE THREAD

**Issue by heidivanparys** [SEMICeu/CAMSS_CSSV#7] opened 2019-11-20 15:04 UTC
Some of the properties could probably be expressed with properties from the [DCMI Metadata Terms](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/). E.g.:

- cssv:LongName → dct:title
- cssv:ShortName → dct:alternative
- cssv:combines → dct:hasPart
- cssv:combinedIn → dct:isPartOf
- cssv:isDefinedBy → dct:creator

**Comment by isa-camss** [comment] 2019-11-28 08:53
Thank you for the input. We will modify the properties accordingly to your suggestion. We have a problem though with replacing combines with hasPart because what we want to express with this predicate is that certain Specifications involve naturally the use of other Specifications and this is very typical in "families" of Specifications. 

For example, XML-based specifications go frequently together with schematron/XSLT. Instead RDF-based implementations are validated with SHACL shapes. 

Possibly the problem is that the predicates "combines" is not good either and we should come up with a predicate that reflects more accuratly this idea of "Family" of specifications.

**Comment by EmidioStani** [comment] 2022-08-22 08:01
This repository is going to be archived, thus I am closing this issue.

**Closed as completed by EmidioStani** 2022-08-22 08:01 UTC
